- .github/workflows/workflows copy/index.yml
- .github/workflows/workflows copy/lint.yml
Added linter for affected tag in PR's
Closes #19
>  ✅ (CI/CD) : Linter

- apps/the-au-pair/src/theme/variables.scss
Added all of the colours that have been used in designs and mockups to the ionic theme
> Added Colour Themes for Ionic

- .github/workflows/CI.yml
fixed incorrect call to merge-report script
> 🚑️(Hotfix) : script rename

- Server/src/main/java/Database/TheAuPair/Controllers/ActivityController.java
- Server/src/main/java/Database/TheAuPair/Controllers/ChildController.java
- Server/src/main/java/Database/TheAuPair/Controllers/ParentController.java
- Server/src/main/java/Database/TheAuPair/Controllers/UserController.java
- Server/src/main/java/Database/TheAuPair/Controllers/auPairController.java
- Server/src/main/java/Database/TheAuPair/Controllers/medAidController.java
- Server/src/main/java/Database/TheAuPair/Models/Activity.java
- Server/src/main/java/Database/TheAuPair/Models/medAid.java
- Server/src/main/java/Database/TheAuPair/Repositories/ActivityRepository.java
- Server/src/main/java/Database/TheAuPair/Repositories/ChildRepository.java
- Server/src/main/java/Database/TheAuPair/Repositories/ParentRepository.java
- Server/src/main/java/Database/TheAuPair/Repositories/UserRepository.java
- Server/src/main/java/Database/TheAuPair/Repositories/auPairRepository.java
- Server/src/main/java/Database/TheAuPair/Repositories/medAidRepository.java
- Server/src/main/java/Database/TheAuPair/TheAuPairApplication.java
- apps/the-au-pair/src/app/app.module.ts
- libs/shared/api/api.service.ts
- libs/shared/interfaces/activity.interfaces.ts
Initial structure and first use case functionality 
- Added Controllers for all collections
- Added API service for Angular
Closes #28 
Closes #47 
Closes #46
> 👽️(API) :  Initial API

- libs/shared/api/api.service.ts
Fixed function name for API service
> 🎨(API) : Function rename

- libs/shared/interfaces/activity.interfaces.ts
Added missing field to Activity interface
> 🎨(API) : Field added to interface

- libs/parent-add-activity/feature/src/lib/parent-add-activity-feature.module.ts
- libs/parent-add-activity/feature/src/lib/parent-add-activity.component.html
- libs/parent-add-activity/feature/src/lib/parent-add-activity.component.scss
- libs/parent-add-activity/feature/src/lib/parent-add-activity.component.spec.ts
- libs/parent-add-activity/feature/src/lib/parent-add-activity.component.ts
- package.json
- Added error checks for empty input fields
- Added unit tests for add activity functions
- Added command to test all front-end code
> 💄✅(UI + Unit tests): Add Activity - Error checking for input fields and unit tests

- Server/src/main/java/Database/TheAuPair/Controllers/ParentController.java
- Server/src/main/java/Database/TheAuPair/Repositories/ParentRepository.java
- libs/shared/api/api.service.ts
Added new service to get Parent by id
> 👽️(API) : Added new service

- libs/parent-add-activity/feature/src/lib/parent-add-activity-feature.module.ts
- libs/parent-add-activity/feature/src/lib/parent-add-activity.component.html
- libs/parent-add-activity/feature/src/lib/parent-add-activity.component.scss
- libs/parent-add-activity/feature/src/lib/parent-add-activity.component.spec.ts
- libs/parent-add-activity/feature/src/lib/parent-add-activity.component.ts
- libs/shared/api/api.service.ts
- package.json
- Used API service to dynamically populate the children from the 'logged in' user.
- Used API to populate database from input activity details.
- Fixed some styling to align some labels.
- Added command to start the API.
> 💄 👽️(UI + API usage): Add Activity - Dynamically populate fields using API

- Server/src/main/java/Database/TheAuPair/Controllers/ActivityController.java
Created function for id generation for use when adding an Activity to the DB
> 👽️(API) : ID generation

- Server/src/main/java/Database/TheAuPair/Controllers/ActivityController.java
- Server/src/main/java/Database/TheAuPair/Repositories/ActivityRepository.java
- Server/src/test/java/Database/TheAuPair/ActivityRepositoryTests.java
Updated getSchedule Query to order by timeStart
> 🗃️(API) : Updated Query

- libs/parent-add-activity/feature/src/lib/parent-add-activity.component.html
- Added correct time slots for the times earlier in the morning
> 🚑️(Hotfix): Fixed time-slot for earlier times

- libs/au-pair-cost/feature/src/lib/au-pair-cost.component.spec.ts
- libs/parent-add-activity/feature/src/lib/parent-add-activity.component.spec.ts
Fixed issues caused by not having RouterTestingModule and NavBarModule
> 🚑️(Hotfix): Hotfix for tests

- README.md
Added the final demo video link and usage instructions for The Au Pair
> 📝: README updated

- package.json
Renamed client start command for consistency with the server start command
> 🔨(Repo) : Rename of command

- Server/src/main/java/Database/TheAuPair/Controllers/ActivityController.java
- Server/src/main/java/Database/TheAuPair/Controllers/ChildController.java
- Server/src/main/java/Database/TheAuPair/Controllers/ParentController.java
- Server/src/main/java/Database/TheAuPair/Controllers/UserController.java
- Server/src/main/java/Database/TheAuPair/Controllers/auPairController.java
- Server/src/main/java/Database/TheAuPair/Controllers/medAidController.java
- Server/src/main/java/Database/TheAuPair/Services/ActivityService.java
- Server/src/main/java/Database/TheAuPair/Services/ChildService.java
- Server/src/main/java/Database/TheAuPair/Services/ParentService.java
- Server/src/main/java/Database/TheAuPair/Services/UserService.java
- Server/src/main/java/Database/TheAuPair/Services/auPairService.java
- Server/src/main/java/Database/TheAuPair/Services/medAidService.java
- Server/src/main/java/Database/TheAuPair/TheAuPairApplication.java
Restructure of the backend to be more standardized and conform to our architecture choice
Closes #101
> 🎨(API) : Restructure of backend

- Server/src/main/java/Database/TheAuPair/Controllers/ActivityController.java
- Server/src/main/java/Database/TheAuPair/Repositories/ActivityRepository.java
- Server/src/main/java/Database/TheAuPair/Services/ActivityService.java
- libs/shared/api/api.service.ts
Added functions to allow for getting activity and editing that activity
Closes #109 
Closes #108
> ✨(API) : Added functions for Activity Service

- .github/workflows/CI.yml
Added flags to pick correct dependencies when installing node
> 💚(CI/CD) : Fixed install of node

- Server/src/main/java/Database/TheAuPair/Controllers/ChildController.java
- Server/src/main/java/Database/TheAuPair/Repositories/ChildRepository.java
- Server/src/main/java/Database/TheAuPair/Services/ChildService.java
- libs/parent-add-activity/feature/src/lib/parent-add-activity.component.spec.ts
- libs/parent-add-activity/feature/src/lib/parent-add-activity.component.ts
- libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.ts
- libs/shared/api/api.service.ts
- libs/shared/interfaces/interfaces.ts
Added functions to allow for adding a Child to the DB and retrieving all children of a parent given their id
Closes #111 
Closes #110
> ✨(API) : Added functions for Children Service

- Server/src/main/java/Database/TheAuPair/Controllers/ParentController.java
- Server/src/main/java/Database/TheAuPair/Controllers/UserController.java
- Server/src/main/java/Database/TheAuPair/Controllers/medAidController.java
- Server/src/main/java/Database/TheAuPair/Repositories/medAidRepository.java
- Server/src/main/java/Database/TheAuPair/Services/ParentService.java
- Server/src/main/java/Database/TheAuPair/Services/UserService.java
- Server/src/main/java/Database/TheAuPair/Services/medAidService.java
- Server/src/main/java/Database/TheAuPair/TheAuPairApplication.java
- libs/shared/api/api.service.ts
- libs/shared/interfaces/interfaces.ts
Added functions to allow for getting a medical aid details
Added edit functions for parent, user and medical aid
Closes #121 
Closes #120 
Closes #112
> ✨(API) : Added functions for Parent, User and MedicalAid Service

- Server/src/main/java/Database/TheAuPair/Controllers/ActivityController.java
- Server/src/main/java/Database/TheAuPair/Controllers/ChildController.java
- Server/src/main/java/Database/TheAuPair/Controllers/ParentController.java
- Server/src/main/java/Database/TheAuPair/Controllers/UserController.java
- Server/src/main/java/Database/TheAuPair/Controllers/auPairController.java
- Server/src/main/java/Database/TheAuPair/Controllers/medAidController.java
- Server/src/main/java/Database/TheAuPair/Models/Child.java
- Server/src/main/java/Database/TheAuPair/Models/auPair.java
- Server/src/main/java/Database/TheAuPair/Repositories/ActivityRepository.java
- Server/src/main/java/Database/TheAuPair/Repositories/ChildRepository.java
- Server/src/main/java/Database/TheAuPair/Repositories/auPairRepository.java
- Server/src/main/java/Database/TheAuPair/Services/ActivityService.java
- Server/src/main/java/Database/TheAuPair/Services/ParentService.java
- Server/src/main/java/Database/TheAuPair/Services/UserService.java
- Server/src/main/java/Database/TheAuPair/Services/auPairService.java
- Server/src/main/java/Database/TheAuPair/Services/medAidService.java
- Server/src/test/java/Database/TheAuPair/auPairRepositoryTests.java
- libs/au-pair-cost/feature/src/lib/au-pair-cost.component.ts
- libs/au-pair-schedule/feature/src/lib/au-pair-schedule.component.ts
- libs/parent-add-activity/feature/src/lib/parent-add-activity.component.ts
- libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.ts
- libs/schedule/feature/src/lib/schedule.ts
- libs/shared/api/api.service.ts
minor fixes due to adjustment of DB schema and code reformatting 
Closes #123
> 🎨(API) : Code Cleanup

- Server/src/main/java/Database/TheAuPair/Controllers/hoursLoggedController.java
- Server/src/main/java/Database/TheAuPair/Models/hoursLogged.java
- Server/src/main/java/Database/TheAuPair/Repositories/hoursLoggedRepository.java
- Server/src/main/java/Database/TheAuPair/Services/hoursLoggedService.java
- Server/src/main/java/Database/TheAuPair/TheAuPairApplication.java
- libs/shared/api/api.service.ts
- libs/shared/interfaces/interfaces.ts
Added the back-end functionality for Au Pairs to log the number of hours they work
> Created Logging Hours API

- Server/src/main/java/Database/TheAuPair/Models/medAid.java
Added field for provider and methods to access it
Closes #128
> 👽️(API) : Updated MedicalAid Model

- Server/src/main/java/Database/TheAuPair/Models/Child.java
- Server/src/main/java/Database/TheAuPair/Repositories/ChildRepository.java
- Server/src/main/java/Database/TheAuPair/Services/ChildService.java
added function to get children using an AuPairI D
> 👽️(API) : updated Child model and functions

- libs/add-child/feature/src/lib/add-child.component.html
- libs/add-child/feature/src/lib/add-child.component.scss
- libs/add-child/feature/src/lib/add-child.component.spec.ts
- libs/add-child/feature/src/lib/add-child.component.ts
- API usage to add a child to the database
- Unit testing for checking valid forms
- Unit testing for checking invalid forms
- Integration testing to ensure correct functions are called within functions
- Error checking for valid SA ID numbers
> 👽️✅ (API + tests): Add Child page integrated with API, Unit + Integration tests complete.

- libs/children-dashboard/feature/src/lib/children-dashboard-feature.module.ts
- libs/children-dashboard/feature/src/lib/children-dashboard.component.html
- libs/children-dashboard/feature/src/lib/children-dashboard.component.scss
- libs/children-dashboard/feature/src/lib/children-dashboard.component.ts
- Added children dynamically to the dashboard according to the logged in user
- Added styling to change the view for mobile
> 👽️💄 (API + Styling) : API for children dashboard and styling for mobile view

- Server/src/main/java/Database/TheAuPair/Models/Activity.java
Changed behaviour to be a integer
> 👽️(API) : Updated Activity model

- libs/parent-add-activity/feature/src/lib/parent-add-activity.component.spec.ts
- libs/parent-add-activity/feature/src/lib/parent-add-activity.component.ts
- libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.spec.ts
- libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.ts
- libs/shared/interfaces/interfaces.ts
> 👽️(API) : updated activity interface

- libs/au-pair-schedule/feature/src/lib/au-pair-schedule.component.html
- libs/au-pair-schedule/feature/src/lib/au-pair-schedule.module.ts
- libs/parent-dashboard/feature/src/lib/parent-dashboard.html
- libs/shared/components/aupair-navbar/.eslintrc.json
- libs/shared/components/aupair-navbar/README.md
- libs/shared/components/aupair-navbar/jest.config.js
- libs/shared/components/aupair-navbar/project.json
- libs/shared/components/aupair-navbar/src/index.ts
- libs/shared/components/aupair-navbar/src/lib/navbar.component.html
- libs/shared/components/aupair-navbar/src/lib/navbar.component.scss
- libs/shared/components/aupair-navbar/src/lib/navbar.component.spec.ts
- libs/shared/components/aupair-navbar/src/lib/navbar.component.ts
- libs/shared/components/aupair-navbar/src/lib/navbar.module.ts
- libs/shared/components/aupair-navbar/src/test-setup.ts
- libs/shared/components/aupair-navbar/tsconfig.json
- libs/shared/components/aupair-navbar/tsconfig.lib.json
- libs/shared/components/aupair-navbar/tsconfig.spec.json
- tsconfig.base.json
- workspace.json
- Make the navbar redirect to the parent dashboard  when on a parent related screen
- Make the navbar redirect to the au pair dashboard when on an au pair related screen
> 🩹 (FIX) : Au Pair Navbar

- libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.spec.ts
- libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.ts
- libs/au-pair-schedule/feature/src/lib/au-pair-schedule.component.spec.ts
- Fixed logging button flipping on and off consecutively 
- Corrected navbar path in testing file for au pair schedule
> 🚑(UI + Tests) Fix for testing and logging button

- Server/pom.xml
- Server/src/main/java/Database/TheAuPair/Controllers/UserController.java
- Server/src/main/java/Database/TheAuPair/Models/User.java
- Server/src/main/java/Database/TheAuPair/Services/SecurityService.java
- Server/src/main/java/Database/TheAuPair/Services/UserService.java
- Server/src/test/java/Database/TheAuPair/UserRepositoryTests.java
- libs/edit-parent-profile/feature/src/lib/edit-parent-profile.component.spec.ts
- libs/edit-parent-profile/feature/src/lib/edit-parent-profile.component.ts
- libs/parent-dashboard/feature/src/lib/parent-dashboard.ts
- libs/parent-profile/feature/src/lib/parent-profile.component.ts
- libs/shared/api/api.service.ts
- libs/shared/interfaces/interfaces.ts
Closes #183 
Closes #182 
Closes #184 
Closes #185
> ✨(API) : Login and Registration Functionality 

- Server/src/main/java/Database/TheAuPair/Controllers/UserController.java
- Server/src/main/java/Database/TheAuPair/Controllers/auPairController.java
- Server/src/main/java/Database/TheAuPair/Repositories/UserRepository.java
- Server/src/main/java/Database/TheAuPair/Services/UserService.java
- Server/src/main/java/Database/TheAuPair/Services/auPairService.java
- libs/shared/api/api.service.ts
> ✨(API) : Added Admin Console Fucntions

- Server/src/main/java/Database/TheAuPair/Controllers/ParentController.java
- Server/src/main/java/Database/TheAuPair/Controllers/auPairController.java
- Server/src/main/java/Database/TheAuPair/Services/ParentService.java
- Server/src/main/java/Database/TheAuPair/Services/SecurityService.java
- Server/src/main/java/Database/TheAuPair/Services/auPairService.java
- libs/login/feature/src/lib/login-feature.module.ts
- libs/login/feature/src/lib/login.component.html
- libs/login/feature/src/lib/login.component.scss
- libs/login/feature/src/lib/login.component.spec.ts
- libs/login/feature/src/lib/login.component.ts
- libs/register/feature/src/lib/register.component.html
- libs/register/feature/src/lib/register.component.scss
- libs/register/feature/src/lib/register.component.spec.ts
- libs/register/feature/src/lib/register.component.ts
- libs/shared/api/api.service.ts
Closes #206 
Closes #205 
Closes #200
> 👽️(API/Feature) : Login and Registration API Integration

- Server/src/main/java/Database/TheAuPair/Controllers/ActivityController.java
- Server/src/main/java/Database/TheAuPair/Controllers/ChildController.java
- Server/src/main/java/Database/TheAuPair/Controllers/ParentController.java
- Server/src/main/java/Database/TheAuPair/Controllers/UserController.java
- Server/src/main/java/Database/TheAuPair/Controllers/auPairController.java
- Server/src/main/java/Database/TheAuPair/Controllers/hoursLoggedController.java
- Server/src/main/java/Database/TheAuPair/Controllers/medAidController.java
Added error handling for bind results and HTTP frame formate
Closes #231
> 🎨(API) : Updated controllers

- Server/src/main/java/Database/TheAuPair/Repositories/ChildRepository.java
- cypress/integration/admin-integration-tests.spec.js
- cypress/integration/aupair-integration-tests.spec.js
- cypress/integration/parent-integration.spec.js
- Integration testing for admins
- Integration testing for au pairs
- Updated integration tests for parents
> ✅ (testing) : Cypress integration testing for au pairs and admins

- libs/login/feature/src/lib/login.component.ts
> Login refresh

- Server/src/main/java/Database/TheAuPair/Models/Activity.java
- apps/the-au-pair/src/app/app.component.ts
- libs/add-child/feature/src/lib/add-child.component.html
- libs/add-child/feature/src/lib/add-child.component.scss
- libs/add-child/feature/src/lib/add-child.component.spec.ts
- libs/add-child/feature/src/lib/add-child.component.ts
- libs/children-dashboard/feature/src/lib/children-dashboard.component.html
- libs/children-dashboard/feature/src/lib/children-dashboard.component.ts
- libs/edit-child/feature/src/lib/edit-child.component.html
- libs/edit-child/feature/src/lib/edit-child.component.scss
- libs/explore/feature/src/lib/explore.component.scss
- libs/hire-requests/feature/src/lib/hire-requests.component.scss
- libs/notifications/feature/src/lib/notifications.component.scss
- libs/parent-add-activity/feature/src/lib/parent-add-activity.component.html
- libs/parent-add-activity/feature/src/lib/parent-add-activity.component.scss
- libs/parent-add-activity/feature/src/lib/parent-add-activity.component.spec.ts
- libs/parent-add-activity/feature/src/lib/parent-add-activity.component.ts
- libs/parent-dashboard/feature/src/lib/parent-dashboard.scss
- libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.html
- libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.scss
- libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.spec.ts
- libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.ts
- libs/parent-view-activity/feature/src/lib/parent-view-activity.component.html
- libs/parent-view-activity/feature/src/lib/parent-view-activity.component.scss
- libs/parent-view-activity/feature/src/lib/parent-view-activity.component.ts
- libs/schedule/feature/src/lib/schedule.html
- libs/schedule/feature/src/lib/schedule.scss
- libs/shared/interfaces/interfaces.ts
- Added a boundary field for activities and updated the database records to include this field.
- Added a limit on the number of children a parent can add.
- Mobile styling enhancements for the following pages:
> Add activity
> Edit activity
> View activity
> Add child
> Edit child
> (💄✅) : New field for activities and UI fixes for activity/children pages 

- Server/src/main/java/Database/TheAuPair/Controllers/ActivityController.java
- Server/src/main/java/Database/TheAuPair/Controllers/ChildController.java
- Server/src/main/java/Database/TheAuPair/Services/ActivityService.java
- Server/src/main/java/Database/TheAuPair/Services/ChildService.java
- Server/src/test/java/Database/TheAuPair/ActivityRepositoryTests.java
- libs/add-child/feature/src/lib/add-child.component.ts
- libs/children-dashboard/feature/src/lib/children-dashboard.component.html
- libs/children-dashboard/feature/src/lib/children-dashboard.component.scss
- libs/children-dashboard/feature/src/lib/children-dashboard.component.spec.ts
- libs/children-dashboard/feature/src/lib/children-dashboard.component.ts
- libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.html
- libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.scss
- libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.ts
- libs/shared/api/api.service.ts
- Functionality to allow parents to delete children from their profile
- Deletes the child as well as all of their associated data (activities) from the database.
- Functionality to allow parents to delete existing activities for a child
> (✨) : Added functionality to delete children and activities

- .github/workflows/CD.yml
- Server/src/main/java/Database/TheAuPair/Controllers/ActivityController.java
- Server/src/main/java/Database/TheAuPair/Controllers/ChildController.java
- Server/src/main/java/Database/TheAuPair/Controllers/ContractController.java
- Server/src/main/java/Database/TheAuPair/Controllers/NotificationsController.java
- Server/src/main/java/Database/TheAuPair/Controllers/ParentController.java
- Server/src/main/java/Database/TheAuPair/Controllers/ReportController.java
- Server/src/main/java/Database/TheAuPair/Controllers/UserController.java
- Server/src/main/java/Database/TheAuPair/Controllers/auPairController.java
- Server/src/main/java/Database/TheAuPair/Controllers/hoursLoggedController.java
- Server/src/main/java/Database/TheAuPair/Controllers/medAidController.java
- libs/shared/api/api.service.ts
- package.json
- tools/scripts/clean-build.js
Closes #287 
Closes #288 
Closes #289 
Closes #290 
Closes #291
> ✅(CI/CD) : Deployment and hosting workflows 

- apps/the-au-pair/src/environments/environment.prod.ts
- apps/the-au-pair/src/environments/environment.ts
- libs/shared/api/api.service.ts
Make use of Environments to for different build targets
Closes #303
> 🔐(Enviroments) : Created Enviroments

- apps/the-au-pair/src/theme/variables.scss
- libs/au-pair-dashboard/feature/src/lib/user-report-modal/user-report-modal.component.scss
- libs/parent-dashboard/feature/src/lib/parent-dashboard.html
- libs/parent-dashboard/feature/src/lib/parent-dashboard.scss
- libs/parent-dashboard/feature/src/lib/user-report-modal/user-report-modal.component.scss
Modal colours were changed for mobile, corners are now rounded, report button positions are now fixed.
Parent dashboard buttons all go away when no au pair is unemployed again.
> Modal Fixes and Parent Dashboard buttons fix

- .github/workflows/CD.yml
- apps/the-au-pair/src/environments/environment.prod.ts
> 💚(Deployment): Updated Deployment

- Server/pom.xml
- Server/src/main/java/Database/TheAuPair/Controllers/StorageController.java
- Server/src/main/java/Database/TheAuPair/S3Config.java
- Server/src/main/java/Database/TheAuPair/Services/StorageService.java
- Server/src/main/resources/application.properties
- libs/shared/api/api.service.ts
API functions for uploading and downloading assets for the app
Closes #315
> ✨(AWS Storage): API functionality for app storage 

- Server/src/main/java/Database/TheAuPair/Controllers/UserController.java
- Server/src/main/java/Database/TheAuPair/Services/UserService.java
- Server/src/main/resources/secrets_template.properties
- apps/the-au-pair/src/app/app.component.ts
- libs/login/feature/src/lib/login.component.spec.ts
- libs/login/feature/src/lib/login.component.ts
- libs/shared/api/api.service.ts
- package.json
Fixed errors in console for the Activities
Dynamic notifications assignment on mobiles
> Dynamic Push notifications for mobile

- Server/src/main/java/Database/TheAuPair/Controllers/FuelCostController.java
- cypress.json
- cypress/integration/admin-integration-tests.spec.js
- cypress/integration/aupair-integration-tests.spec.js
- cypress/integration/parent-integration.spec.js
- cypress/integration/user-integration-tests.spec.js
- libs/shared/components/navbar/src/lib/navbar.component.html
> ✅(Testing): Updated and Added Cypress tests

- apps/the-au-pair/src/app/app.component.html
- libs/au-pair-cost/feature/src/lib/au-pair-cost.component.scss
- libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.html
- libs/au-pair-schedule/feature/src/lib/schedule-modal/schedule-modal.component.ts
- libs/parent-add-activity/feature/src/lib/parent-add-activity.component.html
- libs/parent-dashboard/feature/src/lib/parent-dashboard.html
- libs/parent-edit-activity/feature/src/lib/parent-edit-activity.component.html
- libs/shared/components/navbar/src/lib/navbar.component.html
- Changed "Dashboard" to "home"
- Changed "Return" to "Go Back"
- Made image upload of children at activities optional
- Fixed mobile scaling for au pair costs page with monthly expenses section
> 💄🐛: UI and Bug fixes from usability testing feedback

- .github/workflows/CD.yml
- Server/pom.xml
Updated version label 
changed CD workflow
Closes #382
> 🎨(Version Control)
